DROP TABLE ORGANISMS CASCADE CONSTRAINTS ; 

CREATE TABLE ORGANISMS ( 
  ID       NUMBER        NOT NULL, 
  KINGDOM  VARCHAR2 (50), 
  PHYLUM   VARCHAR2 (50), 
  CLASS    VARCHAR2 (50), 
  ORDER_   VARCHAR2 (50), 
  FAMILY   VARCHAR2 (50), 
  GENUS    VARCHAR2 (50), 
  SPECIES  VARCHAR2 (150), 
  CONSTRAINT XPKORGANISMS
  PRIMARY KEY ( ID ) 
) 
; 

GRANT SELECT ON ORGANISMS TO PUBLIC;

DROP TABLE PROTEINS CASCADE CONSTRAINTS ; 

CREATE TABLE PROTEINS ( 
  ID         NUMBER        NOT NULL, 
  FAMILY     VARCHAR2 (50), 
  CLASS      VARCHAR2 (100), 
  SUBFAMILY  VARCHAR2 (50), 
  CONSTRAINT XPKPROTEINS
  PRIMARY KEY ( ID ) 
) 
; 

GRANT SELECT ON PROTEINS TO PUBLIC;

DROP TABLE SEQUENCES CASCADE CONSTRAINTS ; 

CREATE TABLE SEQUENCES ( 
  PROTEIN_ID   NUMBER, 
  ORGANISM_ID  NUMBER, 
  SEQ_ID       NUMBER        NOT NULL, 
  DESCRIPTION  VARCHAR2 (200), 
  SEQ          VARCHAR2 (4000), 
  SEQ_HASH     BLOB, 
  CONSTRAINT XPKSEQUENCES
  PRIMARY KEY ( SEQ_ID ) 
) 
; 

ALTER TABLE SEQUENCES ADD  CONSTRAINT XFKSEQUENCES_PROTEINS
 FOREIGN KEY (PROTEIN_ID) 
  REFERENCES SEQ.PROTEINS (ID) ;

ALTER TABLE SEQUENCES ADD  CONSTRAINT XFKSEQUENCES_ORGANISMS
 FOREIGN KEY (ORGANISM_ID) 
  REFERENCES SEQ.ORGANISMS (ID) ;


GRANT SELECT ON SEQUENCES TO PUBLIC;
