DROP TABLE TERM CASCADE CONSTRAINTS ; 
CREATE TABLE TERM ( 
  ID           NUMBER ( 38 ) NOT NULL, 
  NAME         VARCHAR2 (255)  NOT NULL, 
  TERM_TYPE    VARCHAR2 (55)  NOT NULL, 
  ACC          VARCHAR2 (255)  NOT NULL, 
  IS_OBSOLETE  NUMBER ( 38 ) NOT NULL, 
  IS_ROOT      NUMBER ( 38 ) NOT NULL, 
  UNIQUE (ACC), 
  PRIMARY KEY ( ID )) 
; 

CREATE INDEX T1 ON 
  TERM(NAME); 

CREATE INDEX T2 ON 
  TERM(TERM_TYPE) ; 
  
  
  
DROP TABLE TERM2TERM CASCADE CONSTRAINTS ; 

CREATE TABLE TERM2TERM ( 
  ID                    NUMBER ( 38 ) NOT NULL, 
  RELATIONSHIP_TYPE_ID  NUMBER ( 38 ) NOT NULL, 
  TERM1_ID              NUMBER ( 38 ) NOT NULL, 
  TERM2_ID              NUMBER ( 38 ) NOT NULL, 
  COMPLETE              NUMBER ( 38 ) NOT NULL, 
  PRIMARY KEY ( ID ) ) 
; 

ALTER TABLE TERM2TERM ADD 
 FOREIGN KEY (RELATIONSHIP_TYPE_ID) 
  REFERENCES TERM (ID) ;

ALTER TABLE TERM2TERM ADD 
 FOREIGN KEY (TERM1_ID) 
  REFERENCES TERM (ID) ;

ALTER TABLE TERM2TERM ADD 
 FOREIGN KEY (TERM2_ID) 
  REFERENCES TERM (ID) ;

CREATE INDEX TT3 ON 
  TERM2TERM(TERM1_ID, TERM2_ID) ; 

CREATE UNIQUE INDEX AK_TERM2TERM ON 
  TERM2TERM(TERM1_ID, TERM2_ID, RELATIONSHIP_TYPE_ID) 
 ; 

CREATE INDEX TT1 ON 
  TERM2TERM(TERM1_ID) 
 ; 

CREATE INDEX TT2 ON 
  TERM2TERM(TERM2_ID) 
; 

CREATE INDEX TT4 ON 
  TERM2TERM(RELATIONSHIP_TYPE_ID) 
; 



DROP TABLE GRAPH_PATH CASCADE CONSTRAINTS ; 

CREATE TABLE GRAPH_PATH ( 
  ID        NUMBER ( 38 ) NOT NULL, 
  TERM1_ID  NUMBER ( 38 ) NOT NULL, 
  TERM2_ID  NUMBER ( 38 ) NOT NULL, 
  DISTANCE  NUMBER ( 38 ) NOT NULL, 
  PRIMARY KEY ( ID ) 
) 
; 

ALTER TABLE GRAPH_PATH ADD 
 FOREIGN KEY (TERM1_ID) 
  REFERENCES TERM (ID) ;

ALTER TABLE GRAPH_PATH ADD 
 FOREIGN KEY (TERM2_ID) 
  REFERENCES TERM (ID) ;

CREATE INDEX GRAPH_PATH1 ON 
  GRAPH_PATH(TERM1_ID)  ; 

CREATE INDEX GRAPH_PATH4 ON 
  GRAPH_PATH(TERM1_ID, DISTANCE) 
; 

CREATE INDEX GRAPH_PATH3 ON 
  GRAPH_PATH(TERM1_ID, TERM2_ID) 
; 

CREATE INDEX GRAPH_PATH2 ON 
  GRAPH_PATH(TERM2_ID) 
; 

